import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 6,
    name: "Siaton Farm",
    image: "/images/brands/siaton.jpg",
    imageLight: "/images/brands/siaton.jpg",
  },
  {
    id: 1,
    name: "Travis",
    image: "/images/brands/travis.jpg",
    imageLight: "/images/brands/travis.jpg",
  },
  {
    id: 2,
    name: "Hukad",
    image: "/images/brands/hukad.jpg",
    imageLight: "/images/brands/hukad.jpg",
  },
  {
    id: 3,
    name: "Potato Corner",
    image: "/images/brands/potatocorner.jpg",
    imageLight: "/images/brands/potatocorner.jpg",
  },
  {
    id: 4,
    name: "Cali",
    image: "/images/brands/Cali.jpeg",
    imageLight: "/images/brands/Cali.jpeg",
  },
  {
    id: 5,
    name: "Kahoy",
    image: "/images/brands/Kahoy.jpg",
    imageLight: "/images/brands/Kahoy.jpg",
  },
  {
    id: 6,
    name: "HOLY CUP",
    image: "/images/brands/holy cup.png",
    imageLight: "/images/brands/holy cup.png",
  },
  {
    id: 7,
    name: "TAO'S NATIVE CHICKEN",
    image: "/images/brands/native.jpg",
    imageLight: "/images/brands/native.jpg",
  },
  {
    id: 8,
    name: "PAN-Q",
    image: "/images/brands/panq.jpg",
    imageLight: "/images/brands/panq.jpg",
  },
  {
    id: 9,
    name: "QU4DROS",
    image: "/images/brands/quadros.jpg",
    imageLight: "/images/brands/quadros.jpg",
  },
  {
    id: 10,
    name: "SCOOBYS",
    image: "/images/brands/scoobys.jpg",
    imageLight: "/images/brands/scoobys.jpg",
  },
  {
    id: 11,
    name: "Cafe icelandia",
    image: "/images/brands/icelandia.png",
    imageLight: "/images/brands/icelandia.png",
  },
  {
    id: 12,
    name: "KA-ON",
    image: "/images/brands/kaon.jpg",
    imageLight: "/images/brands/kaon.jpg",
  },
  {
    id: 13,
    name: "KKOPI TEA",
    image: "/images/brands/kkopi.jpg",
    imageLight: "/images/brands/kkopi.jpg",
  },
  {
    id: 14,
    name: "HOY LUGAW",
    image: "/images/brands/hoylugaw.jpg",
    imageLight: "/images/brands/hoylugaw.jpg",
  },
  {
    id: 15,
    name: "iBake",
    image: "/images/brands/ibake.jpg",
    imageLight: "/images/brands/ibake.jpg",
  },
  {
    id: 16,
    name: "KAPE NEGRENSE BREW",
    image: "/images/brands/kape negrense.png",
    imageLight: "/images/brands/kape negrense.png",
  },
  {
    id: 17,
    name: "KAPENG LOKAL",
    image: "/images/brands/kapenglokal.jpg",
    imageLight: "/images/brands/kapenglokal.jpg",
  },
  {
    id: 18,
    name: "KBOB",
    image: "/images/brands/kbob.jpg",
    imageLight: "/images/brands/kbob.jpg",
  },
  {
    id: 19,
    name: "K.E.L.E Cafe",
    image: "/images/brands/kele.jpg",
    imageLight: "/images/brands/kele.jpg",
  },
  {
    id: 20,
    name: "Lugaw ni Bai",
    image: "/images/brands/lugawnibai.jpg",
    imageLight: "/images/brands/lugawnibai.jpg",
  },
  {
    id: 21,
    name: "Pastry de Marie",
    image: "/images/brands/marie.jpg",
    imageLight: "/images/brands/marie.jpg",
  },
  {
    id: 22,
    name: "Mem's Diner",
    image: "/images/brands/mems.jpg",
    imageLight: "/images/brands/mems.jpg",
  },
  {
    id: 23,
    name: "MOGO",
    image: "/images/brands/mogo.jpg",
    imageLight: "/images/brands/mogo.jpg",
  },
  {
    id: 24,
    name: "Mrs Breadworth's Bakery",
    image: "/images/brands/Mrs Breadworth.png",
    imageLight: "/images/brands/Mrs Breadworth.png",
  },
  {
    id: 25,
    name: "OPHELIAS'S PALABOK",
    image: "/images/brands/ophelias.jpg",
    imageLight: "/images/brands/ophelias.jpg",
  },
  {
    id: 26,
    name: "Rice n' Box",
    image: "/images/brands/rice n box.jpg",
    imageLight: "/images/brands/rice n box.jpg",
  },
  {
    id: 27,
    name: "RYU SUSHI",
    image: "/images/brands/ryu.jpg",
    imageLight: "/images/brands/ryu.jpg",
  },
  {
    id: 28,
    name: "Sauced & Loaded",
    image: "/images/brands/sauced.jpg",
    imageLight: "/images/brands/sauced.jpg",
  },
  {
    id: 29,
    name: "SHABUKO",
    image: "/images/brands/shabuko.jpg",
    imageLight: "/images/brands/shabuko.jpg",
  },
  {
    id: 30,
    name: "Snow Den",
    image: "/images/brands/snowden.png",
    imageLight: "/images/brands/snowden.png",
  },
  {
    id: 31,
    name: "SpLiT CAFE",
    image: "/images/brands/split.png",
    imageLight: "/images/brands/split.png",
  },
  {
    id: 32,
    name: "Chemist Tea",
    image: "/images/brands/tea.jpg",
    imageLight: "/images/brands/tea.jpg",
  },
  {
    id: 33,
    name: "Tealicious",
    image: "/images/brands/tealicious.jpg",
    imageLight: "/images/brands/tealicious.jpg",
  },
  {
    id: 34,
    name: "tiko",
    image: "/images/brands/tiko.jpg",
    imageLight: "/images/brands/tiko.jpg",
  },
  {
    id: 35,
    name: "Turkz",
    image: "/images/brands/turkz.jpg",
    imageLight: "/images/brands/turkz.jpg",
  },
  {
    id: 36,
    name: "UNCLE BREW",
    image: "/images/brands/uncle brew.png",
    imageLight: "/images/brands/uncle brew.png",
  },
  {
    id: 37,
    name: "Wafolicious",
    image: "/images/brands/wafolicious.jpg",
    imageLight: "/images/brands/wafolicious.jpg",
  },
  {
    id: 38,
    name: "XOXO MILKTEA",
    image: "/images/brands/xoxo.jpg",
    imageLight: "/images/brands/xoxo.jpg",
  },
  {
    id: 39,
    name: "Zu Boh Ti TEA",
    image: "/images/brands/zubohti.jpg",
    imageLight: "/images/brands/zubohti.jpg",
  },
  {
    id: 40,
    name: "2story kitchen",
    image: "/images/brands/2story.jpg",
    imageLight: "/images/brands/2story.jpg",
  },
  {
    id: 41,
    name: "ACHARIANS",
    image: "/images/brands/acharian.jpg",
    imageLight: "/images/brands/acharian.jpg",
  },
  {
    id: 42,
    name: "Andok's",
    image: "/images/brands/andoks.jpg",
    imageLight: "/images/brands/andoks.jpg",
  },
  {
    id: 43,
    name: "ANSELMO'S Bistor",
    image: "/images/brands/anselmo.jpg",
    imageLight: "/images/brands/anselmo.jpg",
  },
  {
    id: 44,
    name: "AROMA COFFEE & TEA",
    image: "/images/brands/aroma.jpg",
    imageLight: "/images/brands/aroma.jpg",
  },
  {
    id: 45,
    name: "Baker's Choice Pizza",
    image: "/images/brands/bakers.jpg",
    imageLight: "/images/brands/bakers.jpg",
  },
  {
    id: 46,
    name: "BURGER DELIGHTS",
    image: "/images/brands/burger delights.jpg",
    imageLight: "/images/brands/burger delights.jpg",
  },
  {
    id: 47,
    name: "THE CABIN BLEND",
    image: "/images/brands/cabin.jpg",
    imageLight: "/images/brands/cabin.jpg",
  },
  {
    id: 48,
    name: "Cherie's Cheesecake House",
    image: "/images/brands/cheries.jpg",
    imageLight: "/images/brands/cheries.jpg",
  },
  {
    id: 49,
    name: "Lee CIMBALI",
    image: "/images/brands/cimbali.jpg",
    imageLight: "/images/brands/cimbali.jpg",
  },
  {
    id: 50,
    name: "coffee collective",
    image: "/images/brands/collective.jpg",
    imageLight: "/images/brands/collective.jpg",
  },
  {
    id: 51,
    name: "THE CRUNCH",
    image: "/images/brands/crunch.png",
    imageLight: "/images/brands/crunch.png",
  },
  {
    id: 52,
    name: "DEXTER'S PIZZA",
    image: "/images/brands/dexterpizza.jpg",
    imageLight: "/images/brands/dexterpizza.jpg",
  },
  {
    id: 53,
    name: "MISTER LEE DIMSUM EPXRESS",
    image: "/images/brands/Dimsum logo (2).png",
    imageLight: "/images/brands/Dimsum logo (2).png",
  },
  {
    id: 54,
    name: "DIXON'S BURGER",
    image: "/images/brands/dixons.jpg",
    imageLight: "/images/brands/dixons.jpg",
  },
  {
    id: 55,
    name: "YUMARA DONUTS",
    image: "/images/brands/donuts.jpg",
    imageLight: "/images/brands/donuts.jpg",
  },
  {
    id: 56,
    name: "EGGCITING SNACK BAR",
    image: "/images/brands/eggciting.jpg",
    imageLight: "/images/brands/eggciting.jpg",
  },
  {
    id: 57,
    name: "Flamin GRILL",
    image: "/images/brands/flamin.png",
    imageLight: "/images/brands/flamin.png",
  },
  {
    id: 58,
    name: "FREEZIN' POINT CAFE",
    image: "/images/brands/freezing point.png",
    imageLight: "/images/brands/freezing point.png",
  },
  {
    id: 59,
    name: "Goldilocks",
    image: "/images/brands/goldilocks.jpg",
    imageLight: "/images/brands/goldilocks.jpg",
  },
  {
    id: 60,
    name: "HIGHWAY BLEND",
    image: "/images/brands/highway blend.jpg",
    imageLight: "/images/brands/highway blend.jpg",
  },
  {
    id: 61,
    name: "Ahra's Pizza",
    image: "/images/brands/ahra.jpg",
    imageLight: "/images/brands/ahra.jpg",
  },
  {
    id: 62,
    name: "Brewhouse",
    image: "/images/brands/Brewhouse.jpg",
    imageLight: "/images/brands/Brewhouse.jpg",
  },
  {
    id: 63,
    name: "Cafe Trimo",
    image: "/images/brands/Cafetrimo.jpg",
    imageLight: "/images/brands/Cafetrimo.jpg",
  },
  {
    id: 64,
    name: "Bisnok Pungko-Pungko",
    image: "/images/brands/Bisnok.jpg",
    imageLight: "/images/brands/Bisnok.jpg",
  },
  {
    id: 65,
    name: "Jolan's Calamares",
    image: "/images/brands/Calamares.jpg",
    imageLight: "/images/brands/Calamares.jpg",
  },
  {
    id: 66,
    name: "Dongman's Bellychon",
    image: "/images/brands/Dongmans.jpg",
    imageLight: "/images/brands/Dongmans.jpg",
  },
  {
    id: 67,
    name: "Don Joaquin",
    image: "/images/brands/DonJoaquin.jpg",
    imageLight: "/images/brands/DonJoaquin.jpg",
  },
  {
    id: 68,
    name: "Egg Masarap",
    image: "/images/brands/Eggmasarap.jpg",
    imageLight: "/images/brands/Eggmasarap.jpg",
  },
  {
    id: 69,
    name: "Emiks Mikoy Sushi",
    image: "/images/brands/Emiks.jpg",
    imageLight: "/images/brands/Emiks.jpg",
  },
  {
    id: 70,
    name: "Lutherjohn Special Empanada",
    image: "/images/brands/Empanada.jpg",
    imageLight: "/images/brands/Empanada.jpg",
  },
  {
    id: 71,
    name: "HACIENDA GRILL HOUSE",
    image: "/images/brands/Hacienda.jpg",
    imageLight: "/images/brands/Hacienda.jpg",
  },
  {
    id: 72,
    name: "JUCY PIZZA",
    image: "/images/brands/Jucy.jpg",
    imageLight: "/images/brands/jucy.jpg",
  },
  {
    id: 73,
    name: "Kalapihan COFFEEHOUSE",
    image: "/images/brands/Kalapihan.jpg",
    imageLight: "/images/brands/Kalapihan.jpg",
  },
  {
    id: 74,
    name: "kofinos",
    image: "/images/brands/kofinos.png",
    imageLight: "/images/brands/kofinos.png",
  },
  {
    id: 75,
    name: "KFC",
    image: "/images/brands/KFC.png",
    imageLight: "/images/brands/KFC.png",
  },
  {
    id: 76,
    name: "La LeMON",
    image: "/images/brands/Lalemon.png",
    imageLight: "/images/brands/Lalemon.png",
  },
  {
    id: 77,
    name: "lantaw native restaurant",
    image: "/images/brands/lantaw.jpg",
    imageLight: "/images/brands/lantaw.jpg",
  },
  {
    id: 78,
    name: "LEMON BAY",
    image: "/images/brands/Lemonbay.jpg",
    imageLight: "/images/brands/Lemonbay.jpg",
  },
  {
    id: 79,
    name: "Mang Kaloy",
    image: "/images/brands/Mangkaloy.jpg",
    imageLight: "/images/brands/Mangkaloy.jpg",
  },
  {
    id: 80,
    name: "MACCHIATO COFFEE STATION",
    image: "/images/brands/Macchiato.jpg",
    imageLight: "/images/brands/Macchiato.jpg",
  },
  {
    id: 81,
    name: "Max Mango",
    image: "/images/brands/MaxMango.jpg",
    imageLight: "/images/brands/MaxMango.jpg",
  },
  {
    id: 82,
    name: "PASTAX",
    image: "/images/brands/Pastax.jpg",
    imageLight: "/images/brands/Pastax.jpg",
  },
  {
    id: 83,
    name: "MR FERD CHICKEN",
    image: "/images/brands/Mrferd.jpg",
    imageLight: "/images/brands/Mrferd.jpg",
  },
  {
    id: 84,
    name: "N-JOY'S SNACK STATION",
    image: "/images/brands/Njoys.jpg",
    imageLight: "/images/brands/Njoys.jpg",
  },
  {
    id: 85,
    name: "Rago's Snack Inn",
    image: "/images/brands/Ragos.jpg",
    imageLight: "/images/brands/Ragos.jpg",
  },
  {
    id: 86,
    name: "Shaka's",
    image: "/images/brands/Shakas.jpg",
    imageLight: "/images/brands/Shakas.jpg",
  },
  {
    id: 87,
    name: "XIAH's SUSHi BAR",
    image: "/images/brands/xiahs.jpg",
    imageLight: "/images/brands/xiahs.jpg",
  },
  {
    id: 88,
    name: "Thirstea Snack Haus",
    image: "/images/brands/Thirstea.jpg",
    imageLight: "/images/brands/Thirstea.jpg",
  },
  {
    id: 89,
    name: "TEA SAURUS",
    image: "/images/brands/Teasaurus.jpg",
    imageLight: "/images/brands/Teasaurus.jpg",
  },
  {
    id: 90,
    name: "Socials CAFE",
    image: "/images/brands/Socials.jpg",
    imageLight: "/images/brands/Socials.jpg",
  },
  {
    id: 91,
    name: "Smileys Hamburger",
    image: "/images/brands/Smileys.jpg",
    imageLight: "/images/brands/Smileys.jpg",
  },
  {
    id: 92,
    name: "SIZZLOGAN PREATOOS",
    image: "/images/brands/Sizzlogan.jpg",
    imageLight: "/images/brands/Sizzlogan.jpg",
  },
];

export default brandsData;
